# Generated by Django 5.1.1 on 2024-09-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('stock', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('furniture', 'Bamboo Furniture'), ('fashion', 'Bamboo Fashion'), ('decoration', 'Bamboo Decoration')], max_length=100)),
                ('rating', models.FloatField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('review', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
